<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_XemGioHang</name>
   <tag></tag>
   <elementGuidId>a3534f36-eba3-4bec-a4e9-09001c8eeb7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vng_header']/div/div/ul[2]/li[3]/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ico.ico-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico ico-user</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vng_header&quot;)/div[@class=&quot;container-full&quot;]/div[@class=&quot;header-right&quot;]/ul[@class=&quot;header-tools&quot;]/li[@class=&quot;li-acc li-acc-f&quot;]/div[@class=&quot;tool-myaccount&quot;]/div[@class=&quot;toggle&quot;]/i[@class=&quot;ico ico-user&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vng_header']/div/div/ul[2]/li[3]/div/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[3]/div/div/i</value>
   </webElementXpaths>
</WebElementEntity>
