<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>maSP2</name>
   <tag></tag>
   <elementGuidId>09afa99d-dda2-4d65-9bee-7bfb90313304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id=&quot;shopping-cart-table&quot;]/tbody[2]//*[contains(@class,&quot;item-options&quot;)]/dd[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
